#!/bin/bash
foo="ani"
echo "${foo}ruddha"

tool=execnoop
echo "/usr/share/bcc/tools/${tool}"

echo iovisor-${tool}="docker run --rm -it -v /lib/modules:/lib/modules -v /sys/kernel/debug:/sys/kernel/debug -v /       sys/fs/cgroup:/sys/fs/cgroup -v /sys/fs/bpf:/sys/fs/bpf --privileged --net host --pid host quay.io/iovisor/bcc /usr/share/    bcc/tools/${tool}"
