#!/bin/bash

filename=$1
filenameWithoutExtension=${filename%%.*}
bin_dir="$(pwd)/bin/"

run_gcc() {
    gcc $filename -obin/$filenameWithoutExtension
    ./bin/$filenameWithoutExtension
}

if [[ -f $filename ]]; then
    if [[ -d $bin_dir ]]; then
        echo "Directory ${bin_dir} exists."
        echo $filenameWithoutExtension
        run_gcc
    else
        echo "Error: Directory ${bin_dir} does not exists."
        mkdir $bin_dir
        echo "Directory created"
        run_gcc
    fi
else
    echo "File doesn't exist!"
fi
