#!/bin/bash

filename=$1
filenameWithoutExtension=${filename%%.*}
bin_dir="$(pwd)/bin/"

if [[ -d $bin_dir ]]; then
    echo "Directory ${bin_dir} exists."
    echo $filenameWithoutExtension
    gcc $filename -obin/$filenameWithoutExtension
else
    echo "Error: Directory ${bin_dir} does not exists."
    mkdir $bin_dir
    echo "Directory created"
fi

./bin/$filenameWithoutExtension
